### ISSUE TITLE
Load Errors in UE4 project

### ISSUE THREAD

**Issue by raddman1** [usnistgov/HapticChallengeUE4#1]
**Observed Behavior**
I am seeing a variety of errors on initial project load and when running the scenarios from the editor. I seem to be able to run the scenario fine but just want to make sure this is expected output that can be ignored as opposed to problematic output that may cause issues when playing through the scenarios.

**Steps To Reproduce**
1. Pulled project from repo using sourcetree to fresh directory on local machine
2. Launch 4.20.3 Unreal Engine 
3. Select HapticChallengeUE4 project and click open button
4. View Load Errors in message log and see Can't find file for Asset message as pictured in Initial Load Error Screen show below.
5. Run MainMenu_pick the EMS scenario
6. Notice errors pictured in EMS screenshot
7. Exit run Start again and load Fire Scenario A.
8. Notice errors pictured in FireScenarioA screenshot.

**Screenshots**

![HapticChallengeUE4 Initial Load Error](https://user-images.githubusercontent.com/32369711/57812998-b2062100-773c-11e9-9c00-2696fd223bf0.PNG)

![EMSUE4ErrorsInEditor](https://user-images.githubusercontent.com/32369711/57813129-2214a700-773d-11e9-8710-410872cd9b11.PNG)

![FireScenarioA Load Errors](https://user-images.githubusercontent.com/32369711/57813188-42446600-773d-11e9-8f4d-42b6a2c39a78.PNG)

**Setup (please complete the following information):**

 - OS: Windows 10
 - Headset Errors are occurring independent of headset used
 - Unreal Version 4.20.3
 - Computer Hardware AMD Ryzen 7 2700X Eight-Core Processor 3.7 GHZ, 32 GB Ram, NVIDIA GeForce GTX 1080
 - Room Scale Setup Last tried in Odyssey + at room scale in a 6' X 5' space.

**Additional context**
Just reiterate the application seems to be running fine just want to make sure the errors in the screen captures are not anything I should worry about. Or see if there is anything I should look out for.  I have not played through each scenario yet.

**Comment by jrlvr** [comment]
Hey Raddman,
Some in-progress work was accidentally pushed earlier today which caused the map load errors. A new version has been pushed with fixes to the map load errors and various other bugs.

Best,
Jack

![LoadErrors_Issue1](https://user-images.githubusercontent.com/29755903/57816164-8cc2e400-7737-11e9-9183-97eb9b352072.PNG)
