### ISSUE TITLE
NameEntryMap displayed as non-stereoscopic image in HMD

### ISSUE THREAD

**Issue by AshishMBakshi** [usnistgov/HapticChallengeUE4#2]
**Observed Behavior**
After selecting "Scenarios" in the main menu and choosing one of the scenarios, the user is shown what appears to be NameEntryMap -- but it is enlarged, cut off, and displayed in non-stereoscopic form (more visible in the left eye than the right). There is then no way to enter a name or proceed into a scenario.

Pressing the menu button shows the controller-tracked menu (albeit visible behind the NameEntryMap flat display, and thus visible only to the right eye), from which one can exit back to the main menu.

**Steps To Reproduce**

1. Pull project from GitHub repo to folder on local machine
2. Launch 4.20.3 Unreal Engine
3. Open HapticChallengeUE4 project
4. Run MainMenu_P
5. Select "Scenarios"
6. Select any of the three scenarios
7. Notice the entire FoV of the left eye, and most of the right eye, consumed by a non-stereoscopic blue image with cut-off contents, as in the screenshot

**Screenshots**
![NameEntryBug](https://user-images.githubusercontent.com/2073983/58601223-e6f29780-8255-11e9-9359-f324428d529d.png)

**Setup:**
 - OS: Windows 10
 - Headset: same issue with multiple HMDs (Samsung Odyssey, HP WMR, etc.)
 - Unreal Version 4.20.3
 - Computer Hardware: AMD Ryzen 7 1800X (8-core), 32 GB RAM, 1 TB NVMe SSD, Nvidia GeForce GTX 1080 Ti (also replicated on Microsoft Surface Book 2: Intel Core i7-8650U (4-core), 16 GB RAM, 1 TB NVMe SSD, Nvidia GeForce GTX 1060)
 - Room Scale Setup: 5 x 5' space

**Comment by jrlvr** [comment]
Hey Ashish,
Unfortunately we have not been able to replicate this issue on our end. So, I would like to get a bit more info on this issue if possible.
- Does this happen in both a build and in editor?
- If this does happen in a build, does it happen in all basic build configs? (testing, dev, shipping etc.)
- Are you using SteamVR with the mixed reality plugin or just the mixed reality portal?

Best,
Jack

**Comment by AshishMBakshi** [comment]
Thanks Jack. The issue occurs in all in-editor modes (Preview in VR, Launch) -- but we've since gotten it to work correctly in a packaged build (dev config) at least, so less of a showstopper issue now.

This is with SteamVR with the WMR plugin installed.
